# Traefik Configuration for Enhanced Evernode Hosts
# Version: 3.0 - Optimized for tenant domains and GitHub integration

global:
  checkNewVersion: false
  sendAnonymousUsage: false

# Entry Points
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        options: modern@file

# API and Dashboard
api:
  dashboard: true
  debug: false

# Providers
providers:
  # Docker provider for dynamic service discovery
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik-network
    watch: true
    
  # File provider for static configuration
  file:
    filename: /dynamic.yml
    watch: true

# Certificate Resolvers
certificatesResolvers:
  # Cloudflare DNS-01 Challenge (Recommended)
  cloudflare:
    acme:
      email: "${ACME_EMAIL:-admin@evernode-enhanced.io}"
      storage: /acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 30
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
        disablePropagationCheck: true
        
  # HTTP-01 Challenge (Fallback)
  letsencrypt:
    acme:
      email: "${ACME_EMAIL:-admin@evernode-enhanced.io}"
      storage: /acme.json
      httpChallenge:
        entryPoint: web

# Logging
log:
  level: INFO
  filePath: "/var/log/traefik/traefik.log"
  
accessLog:
  filePath: "/var/log/traefik/access.log"
  bufferingSize: 100
  filters:
    statusCodes:
      - "400-499"
      - "500-599"
    minDuration: "100ms"

# Metrics for monitoring
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

# Tracing (optional)
tracing:
  jaeger:
    samplingType: const
    samplingParam: 1.0

# ServersTransport (for backend connections)
serversTransport:
  insecureSkipVerify: false
  maxIdleConnsPerHost: 10
  dialTimeout: "30s"